name: Compile
on:
  push:
    branches: [main]

jobs:
  compile:
    name: Compile TypeSpec contracts into OpenAPI spec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: bun install
      - run: bun compile
